# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Webjeda cards
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Webjeda Cards is a Bootstrap based jekyll theme for portfolio, photography or any kind of blog.
  
  
  
baseurl: "https://esthercordova.github.io/powerofyet-blog/" # the subpath of your site, e.g. /blog
# baseurl: "/blog" # the subpath of your site, e.g. /blog
mainsiteurl: "https://esthercordova.github.io/powerofyet/"
url: "" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: powerofyet
copyright:
   name: powerofyet
   link: 'http://blog.webjeda.com'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-97310312-1

# Comments
disqus-shortname: http-powerofyet-com

#social
facebook: http://facebook.com/powerofyet
# quora: http://quora.com/sharathdt
# twitter: http://twitter.com/@webjeda
# github: http://github.com/webjeda

#facebook like box
fb-app-id: 549480635219583
fb-page-url: https://www.facebook.com/powerofyet/
fb-page-title: powerofyet

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag]

